
name: CI
 
on: 
  push: 
    branches: [ main  ] 
  pull_request: 
    branches: [ main  ] 
jobs: 
  build: 
    runs-on:  ubuntu-latest 
    steps: 
    - uses: actions/checkout@v2 
    - name: Set Up Python 3.5
      uses: actions/setup-python@v1
      with:
       python-version: 3.8.16
    - name: Install dependencies
      run: |
       make lint
    - name: test with pytest
      run: |
       make test
    - name: Format code
      run: |
       make format
       
       
